name: CI-Build
on: [push, pull_request]

jobs:
  build:
    name: CI-build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install
        run: npm install

      - name: Clean Install
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build
